# Copy this file to config.py and fill in your values
TELEGRAM_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
TELEGRAM_GROUP_ID = "YOUR_GROUP_CHAT_ID"

PORT = 5000
HOST = "0.0.0.0"

DEFAULT_RISK_PERCENT = 1

PAIRS = ["GBPUSD", "EURUSD", "USDJPY", "XAUUSD", "AUDUSD", "GBPJPY", "US30", "NASDAQ", "BTCUSD"]
